// <auto-generated />
namespace Bow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class otras_tablas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(otras_tablas));
        
        string IMigrationMetadata.Id
        {
            get { return "201507060625267_otras_tablas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
