// <auto-generated />
namespace Bow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class tablas_usuario_mensaje_pregunta_respuesta_tipo_puntaje_dimension_juego : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablas_usuario_mensaje_pregunta_respuesta_tipo_puntaje_dimension_juego));
        
        string IMigrationMetadata.Id
        {
            get { return "201504010522434_tablas_usuario_mensaje_pregunta_respuesta_tipo_puntaje_dimension_juego"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
