// <auto-generated />
namespace Bow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class tabla_cases : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tabla_cases));
        
        string IMigrationMetadata.Id
        {
            get { return "201507060440223_tabla_cases"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
