// <auto-generated />
namespace Bow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class campo_estado_tablas_faqs_pregunta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(campo_estado_tablas_faqs_pregunta));
        
        string IMigrationMetadata.Id
        {
            get { return "201504090952586_campo_estado_tablas_faqs_pregunta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
