// <auto-generated />
namespace Bow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class tabla_faqs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tabla_faqs));
        
        string IMigrationMetadata.Id
        {
            get { return "201503200440562_tabla_faqs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
